# https://quarto.org/docs/publishing/github-pages.html#example-knitr-with-renv
on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: ucbscf/stat20-course-materials:latest

    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          path: master

      - name: pwd
        run: pwd

      - name: work around permission issue
        run: |
          git config --global --add safe.directory /__w/quarto-plotly/quarto-plotly

      - name: what do we have here?
        run: find .

      - name: quarto render
        run: quarto render

      - name: what do we have here now?
        run: find .

      - name: git branch
        run: git branch

      - name: Check out gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages

      - name: pwd
        run: pwd

      - name: what is in gh-pages?
        run: find .

      #- name: quarto publish gh-pages
      #  run: quarto publish gh-pages --log-level=debug --no-prompt --no-browser --no-render

      #- name: Render and Publish
      #  uses: quarto-dev/quarto-actions/publish@v2
      #  with:
      #    target: gh-pages
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
