# https://quarto.org/docs/publishing/github-pages.html#example-knitr-with-renv
on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: ucbscf/stat20-course-materials:latest

    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          path: master

      - name: Check out gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages

      - name: Work around permission issue
        run: |
          ( cd master ; git config --global --add safe.directory /__w/quarto-plotly/quarto-plotly/master )
          ( cd gh-pages ; git config --global --add safe.directory /__w/quarto-plotly/quarto-plotly/gh-pages )

      - name: quarto render
        run: ( cd master ; quarto render )

      - name: Copy rendered output to gh-pages
        run: |
          cd master
          rsync -av index.html about.html site_libs ../gh-pages/

      - name: Commit and push rendered output
        run: |
          cd gh-pages
          git config --global user.email "rylo@berkeley.edu"
          git config --global user.name "Ryan Lovett"
          git commit -m "github actions commit."
          git push

      #- name: Render and Publish
      #  uses: quarto-dev/quarto-actions/publish@v2
      #  with:
      #    target: gh-pages
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
